version: '3.2'

services:
  iris:
    image: store/intersystems/irishealth-community:2021.1.0.205.0
    container_name: irishealth
    ports:
    - "1972:1972"
    - "52773:52773"
    volumes:
    - ./shared:/shared
    #environment:
    #- ISC_DATA_DIRECTORY=/shared/durable
